apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: frontend-to-order
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["*"]
    to:
    - operation:
        paths: [/login]
