apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: order-validate-jwt
  namespace: online-shop
spec:
  selector:
    matchLabels:
      run: online-shop-order
  jwtRules:
  - issuer: "https://accounts.google.com"
    jwksUri: "https://www.googleapis.com/oauth2/v3/certs"